### ISSUE TITLE
Generate content from Path milestones 

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#603]
**Is your feature request related to a problem? Please describe.**
Currently, [Path milestones](https://liferay.design/handbook/grow/transversal-skills/excellence/) are stored in two separate places — the Google Docs (where they are turned into JSON and used by path.liferay.design) and in the markdown files in the handbook.

This is not ideal, because any update would require time-consuming copy/pasting — which is annoying and not sustainable.

**Describe the solution you'd like**
Best case scenario — we somehow share the JSON file with the path tool. Second best, would be to copy/paste that into this repo, and then have it parsed and used wherever necessary.

**Comment by plhnk** [comment]
- [ ] use some kind of json-remark plugin
- [ ] probably need to modify the path.liferay.design data model
- [ ] write queries to get the content
- [ ] rewrite all of the grow pages to use queries instead of markdown

**Comment by plhnk** [comment]
fixed in #702
